name: x_health
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: 
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.14.0+1
  meta: 
  url_launcher:

# maps
  google_maps_flutter: 
  google_maps_flutter_web: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
